spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fastcampus
    username: root
    password: admin0000!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate.ddl-auto: create
    show-sql: true
